FROM node

RUN apt-get update && \
    apt-get install -y vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY package.json ./

RUN npm install


COPY . .

# CMD ["npm", "--inspect 0.0.0.0:9229", "node_modules/.bin/react-scripts", "start"]
CMD ["npm", "start"]