FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .


RUN dotnet restore "services/Rediscuss.IdentityService/Rediscuss.IdentityService.csproj"
RUN dotnet publish "services/Rediscuss.IdentityService/Rediscuss.IdentityService.csproj" -o out


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/out .
ENTRYPOINT [ "dotnet", "Rediscuss.IdentityService.dll" ]