FROM node:24 AS build
WORKDIR /app

COPY ./services/Rediscuss.ForumService/ .

RUN npm install
RUN npm run build

FROM node:24-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
EXPOSE 3000

CMD ["node", "dist/src/main"]