FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "services/Rediscuss.ForumService/Rediscuss.ForumService.csproj"
RUN dotnet publish "services/Rediscuss.ForumService/Rediscuss.ForumService.csproj" -o out


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/out .
ENTRYPOINT [ "dotnet", "Rediscuss.ForumService.dll" ]