version : "3.8"


services: 
  rediscuss-ui:
    container_name: rediscuss-ui-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - 3000:3000
    - 9229:9229
    volumes:
    - .:/app
    - /app/node_modules
    environment:
    - WATCHPACK_POLLING=true