FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "services/Rediscuss.ApiGateway/Rediscuss.ApiGateway.csproj"
RUN dotnet publish "services/Rediscuss.ApiGateway/Rediscuss.ApiGateway.csproj" -o out


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/out .
ENTRYPOINT [ "dotnet", "Rediscuss.ApiGateway.dll" ]